CREATE TABLE book (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    description TEXT
);

-- Inserir 50 registros de exemplo na tabela book
INSERT INTO book (title, author, description)
VALUES ('O Senhor dos Anéis', 'J.R.R. Tolkien', 'Uma aventura épica na Terra Média.'),
       ('Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'A história de um jovem bruxo que descobre seu destino.'),
       ('1984', 'George Orwell', 'Um clássico da distopia que retrata um governo totalitário.'),
       ('Orgulho e Preconceito', 'Jane Austen', 'Um romance clássico sobre amor e preconceito.'),
       ('A Metamorfose', 'Franz Kafka', 'A história de um homem que se transforma em um inseto.'),
       ('A Revolução dos Bichos', 'George Orwell', 'Uma fábula sobre política e poder.'),
       ('Dom Quixote', 'Miguel de Cervantes', 'As aventuras de um cavaleiro que perdeu o juízo.'),
       ('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'Um conto filosófico sobre amizade e amor.'),
       ('Cem Anos de Solidão', 'Gabriel García Márquez', 'A saga de uma família ao longo de várias gerações.'),
       ('Crime e Castigo', 'Fiódor Dostoiévski', 'Um romance psicológico sobre crime e redenção.'),
       ('O Hobbit', 'J.R.R. Tolkien', 'Uma jornada inesperada em busca de um tesouro.'),
       ('Anna Karenina', 'Liev Tolstói', 'Um épico russo sobre amor, traição e sociedade.'),
       ('A Arte da Guerra', 'Sun Tzu', 'Um tratado militar sobre estratégia e táticas.'),
       ('A Divina Comédia', 'Dante Alighieri', 'Uma jornada épica através do Inferno, Purgatório e Paraíso.'),
       ('O Processo', 'Franz Kafka', 'Um homem é processado por um crime misterioso.'),
       ('As Aventuras de Sherlock Holmes', 'Arthur Conan Doyle', 'Um detetive brilhante resolve casos intrigantes.'),
       ('Moby Dick', 'Herman Melville', 'A história de uma obsessão com uma baleia branca.'),
       ('O Retrato de Dorian Gray', 'Oscar Wilde', 'Um retrato envelhecido revela os segredos de seu dono.'),
       ('A Ilíada', 'Homero', 'A epopeia da Guerra de Troia e heróis gregos.'),
       ('A Odisséia', 'Homero', 'A jornada de Ulisses de volta para casa após a Guerra de Troia.'),
       ('Drácula', 'Bram Stoker', 'Um clássico do terror sobre um vampiro sedento de sangue.'),
       ('O Príncipe', 'Nicolau Maquiavel', 'Um guia para governantes sobre como manter o poder.'),
       ('A Guerra dos Tronos', 'George R.R. Martin', 'Intrigas, traições e batalhas pelo trono de Westeros.'),
       ('O Grande Gatsby', 'F. Scott Fitzgerald', 'Uma história de amor e decadência na década de 1920.'),
       ('A Redoma de Vidro', 'Sylvia Plath', 'A vida de uma jovem mulher em colapso.'),
       ('Maus', 'Art Spiegelman', 'A história em quadrinhos do Holocausto e suas consequências.'),
       ('O Nome do Vento', 'Patrick Rothfuss', 'As aventuras de um jovem mago em busca de conhecimento.'),
       ('Hamlet', 'William Shakespeare', 'Uma tragédia sobre vingança e loucura.'),
       ('A Coruja', 'Jørn Riel', 'Uma coleção de contos sobre a vida em uma estação meteorológica no Ártico.'),
       ('O Alquimista', 'Paulo Coelho', 'Uma jornada espiritual em busca do tesouro interior.'),
       ('O Morro dos Ventos Uivantes', 'Emily Brontë', 'Uma história de amor e vingança nas charnecas inglesas.'),
       ('Os Miseráveis', 'Victor Hugo', 'A história de um homem em busca de redenção.'),
       ('O Sol é para Todos', 'Harper Lee', 'Um livro sobre injustiça racial e moralidade.'),
       ('O Jogo do Anjo', 'Carlos Ruiz Zafón', 'Um mistério literário ambientado na Barcelona dos anos 1920.'),
       ('A Sangue Frio', 'Truman Capote', 'A história real de um assassinato brutal em uma cidadezinha.'),
       ('Cemitério Maldito', 'Stephen King',
        'Uma história de terror sobre um cemitério que traz os mortos de volta à vida.'),
       ('A Menina que Roubava Livros', 'Markus Zusak',
        'Uma história sobre a vida na Alemanha durante a Segunda Guerra Mundial.'),
       ('A Hora da Estrela', 'Clarice Lispector', 'A história de uma mulher pobre e solitária na cidade grande.'),
       ('O Médico e o Monstro', 'Robert Louis Stevenson', 'Um clássico do horror sobre a dualidade humana.'),
       ('O Cão dos Baskervilles', 'Arthur Conan Doyle',
        'Um caso misterioso para Sherlock Holmes envolvendo uma fera demoníaca.'),
       ('As Vinhas da Ira', 'John Steinbeck', 'Uma saga sobre uma família durante a Grande Depressão.'),
       ('O Código Da Vinci', 'Dan Brown', 'Um thriller de conspiração sobre segredos religiosos.'),
       ('O Iluminado', 'Stephen King', 'Uma história de terror sobre um hotel assombrado e um pai enlouquecido.'),
       ('A Estrada', 'Cormac McCarthy', 'Uma jornada pós-apocalíptica de pai e filho em busca de sobrevivência.'),
       ('O Diário de Anne Frank', 'Anne Frank', 'Os relatos de uma jovem judia durante a Segunda Guerra Mundial.'),
       ('O Poder do Hábito', 'Charles Duhigg',
        'Um livro sobre como os hábitos moldam nossas vidas e como podemos mudá-los.'),
       ('Os Homens que Não Amavam as Mulheres', 'Stieg Larsson', 'Um mistério sombrio de assassinato e intriga.'),
       ('A Revolta de Atlas', 'Ayn Rand', 'Um épico filosófico sobre individualismo e livre mercado.'),
       ('A Metade Sombria', 'Stephen King', 'Uma família se muda para uma casa assombrada e desencadeia o mal.'),
       ('O Poderoso Chefão', 'Mario Puzo', 'A história épica da família Corleone e seu império do crime.'),
       ('O Cemitério de Praga', 'Umberto Eco',
        'Uma conspiração para incitar o anti-semitismo na Europa do século XIX.'),
       ('O Labirinto dos Espíritos', 'Carlos Ruiz Zafón', 'Um mistério envolvendo segredos e traições em Barcelona.'),
       ('Norwegian Wood', 'Haruki Murakami', 'Uma história de amor e melancolia na Tóquio dos anos 1960.');
